services:
  # front:
  #   build: "./front"
  #   ports:
  #     - "8080:8080"

  database:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      interval: 3s
      retries: 30

  # back:
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   build: "./back"
  #   ports:
  #     - "8000:8000"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
  #   container_name: elasticsearch
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   environment:
  #     - discovery.type=single-node
  #     - ELASTIC_PASSWORD=estestpassword
  #     - ELASTIC_USERNAME=elastictest
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   cap_add:
  #     - IPC_LOCK
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   healthcheck:
  #     test: curl -s http://elasticsearch01:9200 >/dev/null || exit 1
  #     timeout: 30s
  #     interval: 3s
  #     retries: 30

  # rabbitmq:
  #   build: ./rabbitmq
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   healthcheck:
  #     test: rabbitmq-diagnostics check_port_connectivity
  #     timeout: 30s
  #     interval: 3s
  #     retries: 30

  # indexer:
  #   build: ./indexer
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - AMQP_URI=amqp://john123:123456@rabbitmq:5672/demo-vhost
  #     - ELASTICSEARCH_URI=http://elasticsearch:9200